// src/lib/mocks.ts
import type { Listing } from "@/lib/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "pm-1001",
    title: "2-bed Apartment, Smithfield, Dublin 7",
    price: 2350,
    lat: 53.3498, lng: -6.2783,
    kind: "apartment",
    county: "Dublin",
    beds: 2, baths: 1, type: "rent",
    url: "https://www.daft.ie/for-rent/apartment/smithfield-dublin-7",
    images: ["https://picsum.photos/seed/pm1/800/600"],
    address: "Smithfield, Dublin 7",
    createdAt: "2025-08-12T10:00:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-rent/apartment/smithfield-dublin-7" },
      { name: "MyHome", url: "https://www.myhome.ie/rentals/dublin-7" },
    ],
  },
  {
    id: "pm-2011",
    title: "3-bed Semi-D, Douglas",
    price: 395000,
    lat: 51.874, lng: -8.438,
    kind: "house",
    county: "Cork",
    beds: 3, baths: 2, type: "sale",
    url: "https://www.myhome.ie/residential/brochure/douglas-cork/123456",
    images: ["https://picsum.photos/seed/pm2/800/600"],
    address: "Douglas, Cork",
    createdAt: "2025-08-14T15:30:00Z",
    sources: [
      { name: "MyHome", url: "https://www.myhome.ie/residential/brochure/douglas-cork/123456" },
      { name: "Daft", url: "https://www.daft.ie/for-sale/house/douglas-cork" },
    ],
  },
  {
    id: "pm-3022",
    title: "Waterfront Site (0.6 acre), Kenmare",
    price: 165000,
    lat: 51.883, lng: -9.583,
    kind: "house",
    county: "Kerry",
    beds: 0, baths: 0, type: "sale",
    url: "https://www.daft.ie/for-sale/site/kenmare-kerry",
    images: ["https://picsum.photos/seed/pm3/800/600"],
    address: "Kenmare, Co. Kerry",
    createdAt: "2025-08-18T09:45:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-sale/site/kenmare-kerry" },
    ],
  },
  {
    id: "pm-4005",
    title: "1-bed Studio, Galway City Centre",
    price: 1200,
    lat: 53.2707, lng: -9.0568,
    kind: "apartment",
    county: "Galway",
    beds: 1, baths: 1, type: "rent",
    url: "https://www.daft.ie/for-rent/studio/galway-city",
    images: ["https://picsum.photos/seed/pm4/800/600"],
    address: "Eyre Square, Galway",
    createdAt: "2025-08-19T13:15:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-rent/studio/galway-city" },
    ],
  },
  {
    id: "pm-5013",
    title: "4-bed Detached House, Malahide",
    price: 695000,
    lat: 53.4505, lng: -6.1549,
    kind: "house",
    county: "Dublin",
    beds: 4, baths: 3, type: "sale",
    url: "https://www.sherryfitz.ie/buy/house/dublin/malahide",
    images: ["https://picsum.photos/seed/pm5/800/600"],
    address: "Malahide, North Co. Dublin",
    createdAt: "2025-08-20T11:00:00Z",
    sources: [
      { name: "SherryFitz", url: "https://www.sherryfitz.ie/buy/house/dublin/malahide" },
    ],
  },
  {
    id: "pm-6017",
    title: "Studio apartment, Ennis",
    price: 80000,
    lat: 52.8436, lng: -8.9861,
    kind: "apartment",
    county: "Clare",
    beds: 0, baths: 0, type: "sale",
    url: "https://www.daft.ie/for-sale/site/ennis-clare",
    images: ["https://picsum.photos/seed/pm6/800/600"],
    address: "Ennis, Co. Clare",
    createdAt: "2025-08-21T09:20:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-sale/site/ennis-clare" },
    ],
  },
  {
    id: "pm-7024",
    title: "2-bed Apartment, Limerick City Docklands",
    price: 1650,
    lat: 52.668, lng: -8.63,
    kind: "apartment",
    county: "Limerick",
    beds: 2, baths: 2, type: "rent",
    url: "https://www.myhome.ie/rentals/apartment/limerick",
    images: ["https://picsum.photos/seed/pm7/800/600"],
    address: "Docklands, Limerick City",
    createdAt: "2025-08-22T08:00:00Z",
    sources: [
      { name: "MyHome", url: "https://www.myhome.ie/rentals/apartment/limerick" },
    ],
  },
  {
    id: "pm-8031",
    title: "5-bed Country Home, Kilkenny",
    price: 450000,
    lat: 52.6541, lng: -7.2448,
    kind: "house",
    county: "Kilkenny",
    beds: 5, baths: 4, type: "sale",
    url: "https://www.daft.ie/for-sale/house/kilkenny",
    images: ["https://picsum.photos/seed/pm8/800/600"],
    address: "Kilkenny, Co. Kilkenny",
    createdAt: "2025-08-23T12:45:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-sale/house/kilkenny" },
    ],
  },
  {
    id: "pm-9037",
    title: "3-bed Townhouse, Sligo",
    price: 220000,
    lat: 54.2697, lng: -8.4694,
    kind: "house",
    county: "Sligo",
    beds: 3, baths: 2, type: "sale",
    url: "https://www.daft.ie/for-sale/townhouse/sligo",
    images: ["https://picsum.photos/seed/pm9/800/600"],
    address: "Sligo Town, Co. Sligo",
    createdAt: "2025-08-24T14:10:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-sale/townhouse/sligo" },
    ],
  },
  {
    id: "pm-10042",
    title: "1-bed Apartment, Temple Bar",
    price: 1850,
    lat: 53.3456, lng: -6.264,
    kind: "apartment",
    county: "Dublin",
    beds: 1, baths: 1, type: "rent",
    url: "https://www.daft.ie/for-rent/apartment/temple-bar-dublin",
    images: ["https://picsum.photos/seed/pm10/800/600"],
    address: "Temple Bar, Dublin 2",
    createdAt: "2025-08-25T18:30:00Z",
    sources: [
      { name: "Daft", url: "https://www.daft.ie/for-rent/apartment/temple-bar-dublin" },
    ],
  },
];
